server:
  port: 8080
  servlet:
    context-path: /v2
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    profile: desenvolvimento

spring:
  datasource:
    url: jdbc:h2:mem:ph-products-api
    driverClassName: org.h2.Driver
    username: admin
    password: admin
    initialize: true
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /docs
    enabled: true

rest-service:
  alguma-coisa:
    host:
    port: